name: fluent_picacg
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.11.3
  go_router: ^15.0.0
  window_manager: ^0.4.3
  system_theme: ^3.1.2
  system_tray: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/notifications/
    - assets/images/placeholders/

  uses-material-design: true
