name: fluent_picacg
description: "PicACG Desktop, built with Flutter and Fluent UI."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  fluent_ui: ^4.11.3
  go_router: ^15.0.0
  provider: ^6.1.4
  window_manager: ^0.4.3
  system_tray: ^2.0.3
  flutter_single_instance: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/notifications/
    - assets/images/placeholders/

  uses-material-design: true
